sheet_id = "13FUl0852qmqQWHkYKLs2D48J0wimkRnfH24eMOqzVJQ"

[gcp_service_account]
type = "service_account"
project_id = "civic-bruin-493822-n0"
private_key_id = "c36c180d435c2f1a725be41daea471cb4c890cf7"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC2V50/+sJRjdGY
0fpm1QhyzlnrBU3YlEBFzbbljohU4c6qF4yOFTypq+vCR5b0gzg0CT4IkQ1QGUOd
dTOPPJurzxjd7R2lMTGl1obK4ierGh+zpXOFiCuSiqIcOJqOrNIHnm9DANCZpDBo
LUWQCpcruwDkG1v8/Cc+T4uk9Z8HsxzxXXA6CYtmc1sH9F6z93paChR8dS/1FlH4
Ku3rIi6pI/1kcU5WcWUgax05vPVGmyIw3ThoZKEiJ0POLIQ8OO7STWaKmY/iQXK3
UT+NDJap+Qxf+KF0Sf1YGn4M17ta1h4i85XeVVufrZU7FgBZc+XFZzY+EHm0N/0w
uwOcuzMDAgMBAAECggEAJYmA1kB1i1tyKA8mCNBXRmcjjKXRYkIWvyf7vGMsvqij
plFlvoQxsk4xoROiyGBRDClQ62uM/Y3N5RbRD+4ur95Y5KrhHPY1Hco9gnuvJeKh
Xxay4uzm52qBt+SRMMj0Ddx4VCdRSifKTU/wj5gWicqcAtl9BOYV4BZ5DXMBE5Da
5h63UP8lekS6vtUkvYlVUDtV45T+1bwM7N8z8yzbSxtWHAvx2xSrd33kZAu/EjGT
n9U3xt2AiW6BXLRESYpb7x/H5OUfxBl00j+goIhD6NmGw3twrBDp8RWglF9wdvUB
0tZ2aH3Y7Q81VYQ/9iHFmZTORKyMCLlUh79badGDKQKBgQDxZNoSbPsls6iA3/iu
fc7uBvvGeuR491urfMsTwn9ftQX+VLQ8pIHH6dfbFmH2QN6KPuAgNoQhPU/4HqGm
hJVuL7GaR4y31khu7TnrAlMJ0+l2M4WO7HFC1+krPyTIsK0/ZMAmX2vDcGmTeose
FgpPgvYrhcFehyNdOy3dn6Az2wKBgQDBYA/vCliNO/ey+MkBRNpiQ+up6aPfHmMY
2F422BAMLURjUVCXZrp7xE+dclEi8WvW+0yAnyXuPmbar6disnmHzGzahxgGzmKr
KchXDZPsix7lsBWF7SvFpgb/Lltacy4tgFPqeReBfg5xVG5ubuhy5KGjtJ80bTMJ
a5ZA2Cc5+QKBgFrHeJMRVOl6xNWiZN0KBvXQvoKH2L/9FgZJqf1GWaxeYWCh7h4Y
J45MzJZhtnlrL8WBm7vBhLMTYa2Hp3b9yUxktz+zxKGl/htpLyzH9P5vKQ8AlSuI
k5d1pwRSfLzUZHLAqtpDbD1VWv7RSNwJodsA/x6i8HNiEtSO2tLLou2dAoGBAICT
lwSiJG8ESJa/xScK2QotjyzTJRrd4ZZLh5l/4Gu4TZicILIKpERXK3jM4hYR4Fp5
jUyYhWf8JfeShAGkGhqpWleTK+6anBCjH4qChLDrcAfZJPZ/1HL/CffyottpanLm
uOVWzsJTRtckBKl5JSX/z1pCZvk9Aopo9ub20l5BAoGBAISMwIdpYNn7713llxFn
8k/vugVF1lIXEpy3ubulws8MZhOS2sIj7KsT+MC1c4klELn2ELQaRhznNcNPOnsi
REY5ZShs4NGbwUTJ4aGq9CYzmUU/hTMq5BzsxtuI/xbghISGl+I++dWkrPUjmBbK
kocx3MqcTJGZgVnnyxkYH+0y
-----END PRIVATE KEY-----
"""
client_email = "bristol-app@civic-bruin-493822-n0.iam.gserviceaccount.com"
client_id = "100366151308038253663"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bristol-app%40civic-bruin-493822-n0.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
