sheet_id = "13FUl0852qmqQWHkYKLs2D48J0wimkRnfH24eMOqzVJQ"

[gcp_service_account]
type = "service_account"
project_id = "civic-bruin-493822-n0"
private_key_id = "c36c180d435c2f1a725be41daea471cb4c890cf7"
private_key = """-----BEGIN PRIVATE KEY-----

-----END PRIVATE KEY-----
"""
client_email = "bristol-app@civic-bruin-493822-n0.iam.gserviceaccount.com"
client_id = "100366151308038253663"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bristol-app%40civic-bruin-493822-n0.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
